/* Product */
export const SET_SELECTED_PRODUCT = "SET_SELECTED_PRODUCT";
export const GET_PRODUCT_OPTIONS = "GET_PRODUCT_OPTIONS";

/* Base Currency */
export const SET_SELECTED_BASECURRENCY = "SET_SELECTED_BASECURRENCY";
export const GET_BASECURRENCY = "GET_BASECURRENCY";

/* Fixed Table Header */
export const GET_CONTAINER_WIDTH = "GET_CONTAINER_WIDTH";

/* Loader */
export const TOGGLE_LOADER = "TOGGLE_LOADER"