export const FETCH_DATA = 'FETCH_DATA'
export const SET_GRID_DATA = "SET_GRID_DATA"

export const GET_SUBSIDIARY = "GET_SUBSIDIARY"
export const SET_SUBSIDIARY = "SET_SUBSIDIARY"

export const SET_DATE_RANGE = "SET_DATE_RANGE"
export const GET_DATE_CONSTRAINT = "GET_DATE_CONSTRAINT"
export const SET_VALID_DATE_RANGE = "SET_VALID_DATE_RANGE"
export const CHANGE_CONVERT_ALL = "CHANGE_CONVERT_ALL"

export const GET_XSRF_TOKEN = "GET_XSRF_TOKEN"